lpanels:CreateLayout("Load For All", {


-------------Skada√Ê∞Â--------------

		-- {	name = "Skada", parent = "SkadaBarWindowSkada", x_off = 0, y_off = 1,
		-- width= "101%",
		-- height = "100%", 
		-- strata = "BACKGROUND",
		-- level = 4,
		-- anchor_to = "BOTTOM", 
		-- anchor_from = "BOTTOM",
		-- tex_file ="Interface\\AddOns\\LitePanels\\media\\black", 
		-- bg_color = "0 0 0",
		-- bg_alpha = 0.3,
		
		-- border ="Interface\\AddOns\\CWDGMediaPack\\Borders\\fer5",
		-- border_size = 14,
		-- inset = 1,
		-- inset = 1,
		-- bg_color = "0 0 0",            --"1 1 1",
		-- border_alpha = 0
		
		-- },

		-- {	name = "Skada_left", parent = "Skada", x_off = 0, y_off = 0,
		-- width= 1,
		-- height = "100%", 
		-- strata = "BACKGROUND",
		-- level = 4,
		-- anchor_to = "LEFT", 
		-- bg_color = "0 0 0",
		-- bg_alpha = 0.7,		
		-- },
		
		-- {	name = "Skada_right", parent = "Skada", x_off = 0, y_off = 0,
		-- width= 1,
		-- height = "100%", 
		-- strata = "BACKGROUND",
		-- level = 4,
		-- anchor_to = "topright", 
		-- bg_color = "0 0 0",
		-- bg_alpha = 0.7,		
		-- },


	-- {	name = "Skada_top", parent = "Skada", x_off = 0, y_off = 0,
		-- width= "100%",
		-- height = 1, 
		-- strata = "BACKGROUND",
		-- level = 4,
		-- anchor_to = "TOPLEFT", 
		-- bg_color = "0 0 0",
		-- bg_alpha = 0.7,
		-- },

	-- {	name = "Skada_bottom", parent = "Skada", x_off = 0, y_off = 0,
		-- width= "100%",
		-- height = 1, 
		-- strata = "BACKGROUND",
		-- level = 4,
		-- anchor_to = "BOTTOMLEFT", 
		-- bg_color = "0 0 0",
		-- bg_alpha = 0.7,
		-- },
		
		
		
		
	 		 
		{	name = "Panel2",
	        anchor_frame = "holder_MainBar",
	        strata = "BACKGROUND", level = 0,
	        anchor_to = "TOPLEFT", x_off = 0, y_off = -1,
	        width = "100%",
	        height = 56,
			inset={top=1,bottom=1,left=1,right=0},
			bg_alpha = 1,
        },
		{	name = "Panel2Shadow",
		    anchor_frame = "Panel2",
			anchor_to = "TOPLEFT",
			width = "101%",
			height = "106%",
			y_off = 2,
			x_off = -2,
			bg_alpha = 0,
			border = "glowTex",
			border_size = "3",
		},
		{	name = "Panel3",
	        anchor_frame = "holder_MultiBarRightBar",
			parent = "MultiBarRight",
	        strata = "BACKGROUND", level = 0,
	        anchor_to = "TOPLEFT", x_off = 0, y_off = 0,
	        width = "100%",
	        height = "100%",
			inset={top=1,bottom=1,left=1,right=0},
			bg_alpha = 1,
        },
		{	name = "Panel3Shadow",
		    anchor_frame = "Panel3",
			parent = "MultiBarRight",
			anchor_to = "TOPLEFT",
			width = "103%",
			height = "103%",
			y_off = 1,
			x_off = -2,
			bg_alpha = 0,
			border = "glowTex",
			border_size = "3",
		},
		{	name = "Panel4",
	        anchor_frame = "holder_MultiBarBottomRightBar",
			parent = "MultiBarBottomRight",
	        strata = "BACKGROUND", level = 0,
	        anchor_to = "TOPLEFT", x_off = 0, y_off = 0,
	        width = "100%",
	        height = "100%",
			inset={top=1,bottom=1,left=1,right=1},
			bg_alpha = 1,
        },
		{	name = "Panel4Shadow",
		    anchor_frame = "Panel4",
			parent = "MultiBarBottomRight",
			anchor_to = "TOPLEFT",
			width = "108%",
			height = "101%",
			y_off = 1.5,
			x_off = -1,
			bg_alpha = 0,
			border = "glowTex",
			border_size = "3",
		},
		{	name = "Panel5",
	        anchor_frame = "holder_MultiBarLeftBar",
			parent = "MultiBarLeft",
	        strata = "BACKGROUND", level = 0,
	        anchor_to = "TOPLEFT", x_off = 0, y_off = 0,
	        width = "100%",
	        height = "100%",
			inset={top=1,bottom=1,left=1,right=0},
			bg_alpha = 1,
        },
		{	name = "Panel5Shadow",
		    anchor_frame = "Panel5",
			parent = "MultiBarLeft",
			anchor_to = "TOPLEFT",
			width = "103%",
			height = "103%",
			y_off = 1,
			x_off = -2,
			bg_alpha = 0,
			border = "glowTex",
			border_size = "3",
		},
		{	name = "PetActionBarPanel",
		    parent = "PetActionBarFrame",
	        anchor_frame = "holder_PetBar",
	        strata = "BACKGROUND", level = 1,
	        anchor_to = "CENTER", x_off = 0, y_off = 0,
			inset={top=1,bottom=1,left=1,right=1},
	        width = 28,
	        height = "100%",
			bg_alpha = 1,
        },
		{	name = "PetActionBarShadow",
		    anchor_frame = "PetActionBarPanel",
			parent = "PetActionBarFrame",
			anchor_to = "TOPLEFT",
			width = 30,
			height = "101%",
			y_off = 1,
			x_off = -1,
			bg_alpha = 0,
			border = "glowTex",
			border_size = "3",
		},
	    })

lpanels:ApplyLayout(nil, "Load For All")